services:
  api:
    build:
      context: .
      dockerfile: api.Dockerfile
    environment:
      NODE_ENV: production
      PORT: "3000"
    ports:
      - "3000:3000"

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    depends_on:
      - api
    ports:
      - "8080:80"
